### PR TITLE
Added V11 support and fixed build target for .NET 7.0

### LINKED ISSUE #125: Core dll not included for .NET 6 in NuGet package
When installing the package on Umbraco 10 the `Our.Umbraco.GMaps.Core.dll` does not get published, it looks like it's because the NuGet package is not targeting .NET 6, I noticed that the README also mentiones Umbraco 11 but I'd suspect this also doesn't work since that runs on .NET 7

### PR DESCRIPTION
**Pull request by devantler**
In the demo project i suggest changing the xcopy prebuild task to this:

```
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <DataFiles Include="$(SolutionDir)Our.Umbraco.GMaps\App_Plugins\Our.Umbraco.GMaps\*.*" />
    </ItemGroup>

    <Copy SourceFiles="@(DataFiles)"
      DestinationFolder="$(ProjectDir)App_Plugins\Our.Umbraco.GMaps\"
      SkipUnchangedFiles="true" />
  </Target>
```

It works on different OSes than Windows, and thus makes it easier to test out the demos, if unaware.

Closes #125

### CODE REVIEW

**Review by robertjf — APPROVED** [review]

**Comment by robertjf** [comment]
Thanks @devantler - good catch on the project file :)

**Comment by robertjf** [comment]
Hi @devantler I didn't see any of this code in the pull request you submitted - do you want to check and perhaps submit a new one?

**Comment by devantler** [comment]
I added the code mentioned in the last comment to the csproj file in the V11 project, and tested that it worked the same as the xcopy solution. I did not want to make changes to all the other demo projects, as it would require me to test those, and as I am on an M1 Mac, that is a bit challenging :-)

**Comment by robertjf** [comment]
ah, gotcha 👍🏻

**Comment by devantler** [comment]
@robertjf can you add these changes to the prerelease?

**Pull request merged**
